DROP TABLE USERS;
CREATE TABLE USERS (ID INT AUTO_INCREMENT PRIMARY KEY, USERNAME VARCHAR(45), PASSWORD VARCHAR(45), ROLE VARCHAR(45));
INSERT INTO USERS (USERNAME, PASSWORD, ROLE) VALUES ('hello', 'hello123456', 'MANAGER');
INSERT INTO USERS (USERNAME, PASSWORD, ROLE) VALUES ('world', 'world123456', 'NORMAL');
SElect * from USERS;