DROP TABLE USERS;
CREATE TABLE USERS (ID INT AUTO_INCREMENT PRIMARY KEY, USERNAME VARCHAR(45), PASSWORD VARCHAR(45));
INSERT INTO USERS (USERNAME, PASSWORD) VALUES ('hello', 'hello123456');
INSERT INTO USERS (USERNAME, PASSWORD) VALUES ('world', 'world123456');
SElect * from USERS;